export enum TopicEnum {
  ACT = 'ACT',
  ADDRESSES = 'Addresses',
  AGENTS = 'Agents',
  APPOINTEES = 'Appointees',
  ASSESMENTS = 'Assessments',
  ASSETS = 'Assets',
  AUDITS = 'Audits',
  AUTHORIZATION = 'Authorization',
  BNR = 'BNR',
  C_E = 'C&E',
  CASE_MERGE = 'Case Merge',
  CASE_MERGE_REQUEST = 'Case Merge Request',
  CAT = 'CAT',
  CDS = 'CDS',
  CGT = 'CGT',
  CHANGE_CUSTOMER_TYPE = 'Change Customer Type',
  CHANGE_REGISTRATION_NUMBER = 'Change Registration Number',
  CHANGE_SP_NUMBER = 'Change SP Number',
  COLLECTION = 'Collection',
  COMPLIANCE = 'Compliance',
  CONSOLIDATION = 'Consolidation',
  CT = 'CT',
  DIRT = 'DIRT',
  DRS = 'DRS',
  DWT = 'DWT',
  ELEV = 'ELEV',
  EVR = 'EVR',
  EXEMPTIONS = 'Exemptions',
  GRO_DOD = 'GRO DOD',
  INSTALMENTS = 'Instalments',
  INTELLIGENCE = 'Intelligence',
  IT = 'IT',
  IUT = 'IUT',
  LAET = 'LAET'

}
